=== clyhs/okaysoft/core/src/main/resources/init/position.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/position.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE position SYSTEM "position.dtd">

    <position>
    ...
    </position>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT position (subPositions)*>
<!ATTLIST position
    positionName CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT subPositions (position)*>

=== clyhs/okaysoft/core/src/main/resources/init/position.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE position SYSTEM "position.dtd">
<!--
        岗位
-->
<position positionName="岗位">
    <subPositions>
        <position positionName="总经理"/>
        <position positionName="副总经理"/>
        <position positionName="开发工程师">
            <subPositions>
                <position positionName="Java软件工程师"/>
                <position positionName="C++软件工程师"/>
                <position positionName=".Net软件工程师"/>
            </subPositions>
        </position>
        <position positionName="人事专员"/>
    </subPositions>
</position>
